### ISSUE TITLE
JustTrustMe causes Chrome ssl error failed when connect to TLS website

### ISSUE THREAD

**Issue by iamwwc** [Fuzion24/JustTrustMe#45]
Maybe the same problem

https://github.com/Fuzion24/JustTrustMe/issues/41

JustTrustMe causes my chrome ssl failed when I connect SSL website
it said:
```
this site can't be reached
https://google.com

ERR_FAILED
```

Removing JustTrustMe module solved :(

I'm not a Java Developer, just give someone idea to avoid this problem

Following are log about JustTrustMe and luckypatcher(you can ignore its log)

**I hope no one spends the whole day like me to solve this problem.**

```
JustTrustMe: Hooking DefaultHTTPClient for: com.android.chrome
05-18 16:45:46.906 26646 26646 W re-initialized>: type=1400 audit(0.0:295): avc: denied { getattr } for path="/data/data/com.android.chrome" dev="dm-0" ino=3302487 scontext=u:r:isolated_app:s0:c512,c768 tcontext=u:object_r:app_data_file:s0:c512,c768 tclass=dir permissive=0
05-18 16:45:46.910 26646 26646 D JustTrustMe: Hooking DefaultHTTPClient(HttpParams) for: com.android.chrome
05-18 16:45:46.911 26646 26646 D JustTrustMe: Hooking DefaultHTTPClient(ClientConnectionManager, HttpParams) for: com.android.chrome
05-18 16:45:46.912 26646 26646 D JustTrustMe: Hooking SSLSocketFactory(String, KeyStore, String, KeyStore) for: com.android.chrome
05-18 16:45:46.914 26646 26646 D JustTrustMe: Hooking static SSLSocketFactory(String, KeyStore, String, KeyStore) for: com.android.chrome
05-18 16:45:46.917 26646 26646 D JustTrustMe: Hooking SSLSocketFactory(Socket) for: com.android.chrome
05-18 16:45:46.919 26646 26646 D JustTrustMe: Hooking TrustManagerFactory.getTrustManagers() for: com.android.chrome
05-18 16:45:46.923 26646 26646 D JustTrustMe: Hooking HttpsURLConnection.setDefaultHostnameVerifier for: com.android.chrome
05-18 16:45:46.924 26646 26646 D JustTrustMe: Hooking HttpsURLConnection.setSSLSocketFactory for: com.android.chrome
05-18 16:45:46.926 26646 26646 D JustTrustMe: Hooking HttpsURLConnection.setHostnameVerifier for: com.android.chrome
05-18 16:45:46.927 26646 26646 D JustTrustMe: Hooking WebViewClient.onReceivedSslError(WebView, SslErrorHandler, SslError) for: com.android.chrome
05-18 16:45:46.929 26646 26646 D JustTrustMe: Hooking WebViewClient.onReceivedSslError(WebView, int, string, string) for: com.android.chrome
05-18 16:45:46.934 26646 26646 D JustTrustMe: Hooking com.android.org.conscrypt.TrustManagerImpl.checkServerTrusted(X509Certificate[]) for: com.android.chrome
05-18 16:45:46.985 26646 26646 I System.out: Update settings xposed
05-18 16:45:46.983 26646 26646 W boxed_process14: type=1400 audit(0.0:296): avc: denied { open } for path="/data/lp/xposed" dev="dm-0" ino=1720323 scontext=u:r:isolated_app:s0:c512,c768 tcontext=u:object_r:system_data_file:s0 tclass=file permissive=0
05-18 16:45:46.985 26646 26646 W System.err: java.io.FileNotFoundException: /data/lp/xposed: open failed: EACCES (Permission denied)
05-18 16:45:46.986 26646 26646 W System.err:    at libcore.io.IoBridge.open(IoBridge.java:512)
05-18 16:45:46.986 26646 26646 W System.err:    at java.io.RandomAccessFile.<init>(RandomAccessFile.java:274)
05-18 16:45:46.986 26646 26646 W System.err:    at com.chelpus.Л€.Л(Utils.java:6001)
05-18 16:45:46.986 26646 26646 W System.err:    at com.chelpus.Л€.бµЋ(Utils.java:8933)
05-18 16:45:46.986 26646 26646 W System.err:    at com.xposed.XSupport.К(XSupport.java:1342)
05-18 16:45:46.986 26646 26646 W System.err:    at com.xposed.XSupport$28.afterHookedMethod(XSupport.java:1088)
05-18 16:45:46.986 26646 26646 W System.err:    at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:375)
05-18 16:45:46.986 26646 26646 W System.err:    at android.app.ApplicationPackageManager.<init>(<Xposed>)
05-18 16:45:46.986 26646 26646 W System.err:    at android.app.ContextImpl.getPackageManager(ContextImpl.java:237)
05-18 16:45:46.986 26646 26646 W System.err:    at android.content.ContextWrapper.getPackageManager(ContextWrapper.java:94)
05-18 16:45:46.986 26646 26646 W System.err:    at csx.b(PG:13)
05-18 16:45:46.986 26646 26646 W System.err:    at aQv.attachBaseContext(PG:95)
05-18 16:45:46.986 26646 26646 W System.err:    at android.app.Application.attach(Application.java:189)
05-18 16:45:46.986 26646 26646 W System.err:    at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
05-18 16:45:46.986 26646 26646 W System.err:    at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:361)
05-18 16:45:46.986 26646 26646 W System.err:    at android.app.Application.attach(<Xposed>)
05-18 16:45:46.986 26646 26646 W System.err:    at android.app.Instrumentation.newApplication(Instrumentation.java:1103)
05-18 16:45:46.986 26646 26646 W System.err:    at android.app.Instrumentation.newApplication(Instrumentation.java:1087)
05-18 16:45:46.986 26646 26646 W System.err:    at android.app.LoadedApk.makeApplication(LoadedApk.java:983)
05-18 16:45:46.986 26646 26646 W System.err:    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5715)
05-18 16:45:46.986 26646 26646 W System.err:    at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
05-18 16:45:46.986 26646 26646 W System.err:    at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:361)
05-18 16:45:46.986 26646 26646 W System.err:    at android.app.ActivityThread.handleBindApplication(<Xposed>)
05-18 16:45:46.986 26646 26646 W System.err:    at android.app.ActivityThread.-wrap1(Unknown Source:0)
05-18 16:45:46.986 26646 26646 W System.err:    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
05-18 16:45:46.986 26646 26646 W System.err:    at android.os.Handler.dispatchMessage(Handler.java:106)
05-18 16:45:46.986 26646 26646 W System.err:    at android.os.Looper.loop(Looper.java:164)
05-18 16:45:46.986 26646 26646 W System.err:    at android.app.ActivityThread.main(ActivityThread.java:6494)
05-18 16:45:46.986 26646 26646 W System.err:    at java.lang.reflect.Method.invoke(Native Method)
05-18 16:45:46.986 26646 26646 W System.err:    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
05-18 16:45:46.986 26646 26646 W System.err:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
05-18 16:45:46.986 26646 26646 W System.err:    at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:108)
05-18 16:45:46.986 26646 26646 W System.err: Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
05-18 16:45:46.986 26646 26646 W System.err:    at libcore.io.Linux.open(Native Method)
05-18 16:45:46.986 26646 26646 W System.err:    at libcore.io.BlockGuardOs.open(BlockGuardOs.java:207)
05-18 16:45:46.986 26646 26646 W System.err:    at libcore.io.IoBridge.open(IoBridge.java:498)
05-18 16:45:46.986 26646 26646 W System.err:    ... 31 more
05-18 16:45:46.987 26646 26646 W System.err: org.json.JSONException: Value ����������������������������������������� ����������������������������������������������������������������������������������������������������������������������������������������� of type java.lang.String cannot be converted to JSONObject
05-18 16:45:46.987 26646 26646 W System.err:    at org.json.JSON.typeMismatch(JSON.java:111)
05-18 16:45:46.987 26646 26646 W System.err:    at org.json.JSONObject.<init>(JSONObject.java:163)
05-18 16:45:46.987 26646 26646 W System.err:    at org.json.JSONObject.<init>(JSONObject.java:176)
05-18 16:45:46.987 26646 26646 W System.err:    at com.chelpus.Л€.бµЋ(Utils.java:8933)
05-18 16:45:46.987 26646 26646 W System.err:    at com.xposed.XSupport.К(XSupport.java:1342)
05-18 16:45:46.987 26646 26646 W System.err:    at com.xposed.XSupport$28.afterHookedMethod(XSupport.java:1088)
05-18 16:45:46.987 26646 26646 W System.err:    at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:375)
05-18 16:45:46.987 26646 26646 W System.err:    at android.app.ApplicationPackageManager.<init>(<Xposed>)
05-18 16:45:46.987 26646 26646 W System.err:    at android.app.ContextImpl.getPackageManager(ContextImpl.java:237)
05-18 16:45:46.987 26646 26646 W System.err:    at android.content.ContextWrapper.getPackageManager(ContextWrapper.java:94)
05-18 16:45:46.987 26646 26646 W System.err:    at csx.b(PG:13)
05-18 16:45:46.987 26646 26646 W System.err:    at aQv.attachBaseContext(PG:95)
05-18 16:45:46.987 26646 26646 W System.err:    at android.app.Application.attach(Application.java:189)
05-18 16:45:46.987 26646 26646 W System.err:    at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
05-18 16:45:46.987 26646 26646 W System.err:    at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:361)
05-18 16:45:46.987 26646 26646 W System.err:    at android.app.Application.attach(<Xposed>)
05-18 16:45:46.987 26646 26646 W System.err:    at android.app.Instrumentation.newApplication(Instrumentation.java:1103)
05-18 16:45:46.987 26646 26646 W System.err:    at android.app.Instrumentation.newApplication(Instrumentation.java:1087)
05-18 16:45:46.987 26646 26646 W System.err:    at android.app.LoadedApk.makeApplication(LoadedApk.java:983)
05-18 16:45:46.987 26646 26646 W System.err:    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5715)
05-18 16:45:46.987 26646 26646 W System.err:    at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
05-18 16:45:46.987 26646 26646 W System.err:    at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:361)
05-18 16:45:46.987 26646 26646 W System.err:    at android.app.ActivityThread.handleBindApplication(<Xposed>)
05-18 16:45:46.987 26646 26646 W System.err:    at android.app.ActivityThread.-wrap1(Unknown Source:0)
05-18 16:45:46.987 26646 26646 W System.err:    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
05-18 16:45:46.987 26646 26646 W System.err:    at android.os.Handler.dispatchMessage(Handler.java:106)
05-18 16:45:46.987 26646 26646 W System.err:    at android.os.Looper.loop(Looper.java:164)
05-18 16:45:46.987 26646 26646 W System.err:    at android.app.ActivityThread.main(ActivityThread.java:6494)
05-18 16:45:46.987 26646 26646 W System.err:    at java.lang.reflect.Method.invoke(Native Method)
05-18 16:45:46.987 26646 26646 W System.err:    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
05-18 16:45:46.987 26646 26646 W System.err:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
05-18 16:45:46.987 26646 26646 W System.err:    at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:108)
05-18 16:45:46.996 26646 26646 D JustTrustMe: Hooking com.squareup.okhttp.CertificatePinner.check(String,List) (2.5) for: com.android.chrome
05-18 16:45:46.996 26646 26646 D JustTrustMe: OKHTTP 2.5 not found in com.android.chrome-- not hooking
05-18 16:45:46.996 26646 26646 D JustTrustMe: Hooking okhttp3.CertificatePinner.check(String,List) (3.x) for: com.android.chrome
05-18 16:45:46.996 26646 26646 D JustTrustMe: OKHTTP 3.x not found in com.android.chrome -- not hooking
05-18 16:45:46.997 26646 26646 D JustTrustMe: OKHTTP 3.x not found in com.android.chrome -- not hooking OkHostnameVerifier.verify(String, SSLSession)
05-18 16:45:46.997 26646 26646 D JustTrustMe: OKHTTP 3.x not found in com.android.chrome -- not hooking OkHostnameVerifier.verify(String, X509)(
05-18 16:45:47.001 26646 26646 I cr_ChildProcessService: Creating new ChildProcessService pid=26646
05-18 16:45:47.038 26646 26665 I cr_LibraryLoader: Time to load native libraries: 29 ms (timestamps 5987-6016)
05-18 16:45:47.039 26646 26665 I chromium: [INFO:library_loader_hooks.cc(50)] Chromium logging enabled: level = 0, default verbosity = 0
05-18 16:45:47.039 26646 26665 I cr_LibraryLoader: Expected native library version number "74.0.3729.157", actual native library version number "74.0.3729.157"
05-18 16:45:47.424 22819 23118 E chromium: [ERROR:ssl_client_socket_impl.cc(946)] handshake failed; returned -1, SSL error code 1, net_error -2
```

You can see `05-18 16:45:47.424 22819 23118 E chromium: [ERROR:ssl_client_socket_impl.cc(946)] handshake failed; returned -1, SSL error code 1, net_error -2` error message

For fix:
Here are my devices info
```
[af.fast_track_multiplier]: [1]
[audio_hal.period_size]: [192]
[dalvik.vm.appimageformat]: [lz4]
[dalvik.vm.boot-dex2oat-threads]: [4]
[dalvik.vm.dex2oat-Xms]: [64m]
[dalvik.vm.dex2oat-Xmx]: [512m]
[dalvik.vm.dex2oat-threads]: [4]
[dalvik.vm.dexopt.secondary]: [true]
[dalvik.vm.heapgrowthlimit]: [192m]
[dalvik.vm.heapmaxfree]: [8m]
[dalvik.vm.heapminfree]: [512k]
[dalvik.vm.heapsize]: [512m]
[dalvik.vm.heapstartsize]: [8m]
[dalvik.vm.heaptargetutilization]: [0.75]
[dalvik.vm.image-dex2oat-Xms]: [64m]
[dalvik.vm.image-dex2oat-Xmx]: [64m]
[dalvik.vm.image-dex2oat-threads]: [4]
[dalvik.vm.isa.arm.features]: [default]
[dalvik.vm.isa.arm.variant]: [cortex-a53.a57]
[dalvik.vm.isa.arm64.features]: [default]
[dalvik.vm.isa.arm64.variant]: [cortex-a53]
[dalvik.vm.lockprof.threshold]: [500]
[dalvik.vm.stack-trace-dir]: [/data/anr]
[dalvik.vm.usejit]: [true]
[dalvik.vm.usejitprofiles]: [true]
[debug.atrace.tags.enableflags]: [0]
[debug.force_rtl]: [0]
[dev.bootcomplete]: [1]
[drm.service.enabled]: [true]
[gsm.current.phone-type]: [1]
[gsm.network.type]: [Unknown]
[gsm.operator.alpha]: []
[gsm.operator.iso-country]: []
[gsm.operator.isroaming]: [false]
[gsm.operator.numeric]: []
[gsm.sim.operator.alpha]: []
[gsm.sim.operator.iso-country]: []
[gsm.sim.operator.numeric]: []
[gsm.sim.state]: [ABSENT]
[gsm.version.baseband]: [angler-03.88]
[gsm.version.ril-impl]: [Qualcomm RIL 1.0]
[hwservicemanager.ready]: [true]
[init.svc.0KdLl5y]: [stopped]
[init.svc.AoBzJKA]: [stopped]
[init.svc.InputEventFind]: [stopped]
[init.svc.a5vnk13]: [stopped]
[init.svc.adbd]: [running]
[init.svc.atfwd]: [running]
[init.svc.audioserver]: [running]
[init.svc.bootanim]: [stopped]
[init.svc.cameraserver]: [running]
[init.svc.cas-hal-1-0]: [running]
[init.svc.cnd]: [running]
[init.svc.configstore-hal-1-0]: [running]
[init.svc.devstart_sh]: [stopped]
[init.svc.drm]: [running]
[init.svc.flash-nanohub-fw]: [stopped]
[init.svc.fps_hal]: [running]
[init.svc.gatekeeperd]: [running]
[init.svc.gralloc-2-0]: [running]
[init.svc.healthd]: [running]
[init.svc.hidl_memory]: [running]
[init.svc.hostapd]: [stopped]
[init.svc.hwservicemanager]: [running]
[init.svc.imscmservice]: [running]
[init.svc.imsdatadaemon]: [running]
[init.svc.imsqmidaemon]: [running]
[init.svc.installd]: [running]
[init.svc.irsc_util]: [stopped]
[init.svc.keystore]: [running]
[init.svc.lmkd]: [running]
[init.svc.loc_launcher]: [running]
[init.svc.logd]: [running]
[init.svc.logd-reinit]: [stopped]
[init.svc.mcfg-sh]: [stopped]
[init.svc.mdnsd]: [running]
[init.svc.media]: [running]
[init.svc.mediacodec]: [running]
[init.svc.mediadrm]: [running]
[init.svc.mediaextractor]: [running]
[init.svc.mediametrics]: [running]
[init.svc.msm_irqbalance]: [running]
[init.svc.netd]: [running]
[init.svc.netmgrd]: [running]
[init.svc.oem_qmi_server]: [running]
[init.svc.per_mgr]: [running]
[init.svc.per_proxy]: [running]
[init.svc.perfd]: [running]
[init.svc.perfprofd]: [stopped]
[init.svc.qcamerasvr]: [running]
[init.svc.qmuxd]: [running]
[init.svc.qseecomd]: [running]
[init.svc.qti]: [running]
[init.svc.radio-sh]: [stopped]
[init.svc.ril-daemon]: [running]
[init.svc.rmt_storage]: [running]
[init.svc.servicemanager]: [running]
[init.svc.ss_ramdump]: [running]
[init.svc.ssr_setup]: [stopped]
[init.svc.storaged]: [running]
[init.svc.surfaceflinger]: [running]
[init.svc.sysinit]: [stopped]
[init.svc.thermal-engine]: [running]
[init.svc.thermalservice]: [running]
[init.svc.time_daemon]: [running]
[init.svc.tombstoned]: [running]
[init.svc.ueventd]: [running]
[init.svc.usb-hal-1-0]: [running]
[init.svc.vndservicemanager]: [running]
[init.svc.vold]: [running]
[init.svc.webview_zygote32]: [running]
[init.svc.wifi_hal_legacy]: [running]
[init.svc.wificond]: [running]
[init.svc.wpa_supplicant]: [running]
[init.svc.zygote]: [running]
[init.svc.zygote_secondary]: [running]
[keyguard.no_require_sim]: [true]
[logd.logpersistd.enable]: [true]
[media.aac_51_output_enabled]: [true]
[media.recorder.show_manufacturer_and_model]: [true]
[net.bt.name]: [Android]
[net.hostname]: []
[net.lte.ims.data.enabled]: [true]
[net.qtaguid_enabled]: [1]
[net.tcp.default_init_rwnd]: [60]
[net.tcp.delack.default]: [1]
[net.tcp.delack.lte]: [8]
[net.tcp.delack.wifi]: [20]
[net.tcp.usercfg.default]: [0]
[net.tcp.usercfg.lte]: [1]
[net.tcp.usercfg.wifi]: [1]
[net.tethering.noprovisioning]: [true]
[nfc.initialized]: [true]
[persist.audio.fluence.speaker]: [true]
[persist.audio.fluence.voicecall]: [true]
[persist.audio.fluence.voicecomm]: [true]
[persist.audio.product.identify]: [angler]
[persist.camera.cpp.duplication]: [false]
[persist.camera.eis.enable]: [1]
[persist.camera.is_type]: [4]
[persist.data.df.agg.dl_pkt]: [10]
[persist.data.df.agg.dl_size]: [4096]
[persist.data.iwlan.enable]: [true]
[persist.data.mode]: [concurrent]
[persist.data.wda.enable]: [true]
[persist.hwc.mdpcomp.enable]: [true]
[persist.media.treble_omx]: [false]
[persist.radio.adb_log_on]: [0]
[persist.radio.always_send_plmn]: [true]
[persist.radio.apm_sim_not_pwdn]: [1]
[persist.radio.custom_ecc]: [1]
[persist.radio.data_con_rprt]: [true]
[persist.radio.data_no_toggle]: [1]
[persist.radio.eons.enabled]: [false]
[persist.radio.mode_pref_nv10]: [1]
[persist.radio.redir_party_num]: [0]
[persist.radio.ril_payload_on]: [0]
[persist.radio.snapshot_enabled]: [1]
[persist.radio.snapshot_timer]: [2]
[persist.rmnet.data.enable]: [true]
[persist.rmnet.mux]: [enabled]
[persist.sys.dalvik.vm.lib.2]: [libart.so]
[persist.sys.dun.override]: [0]
[persist.sys.locale]: [en-US]
[persist.sys.ssr.enable_ramdumps]: [1]
[persist.sys.ssr.restart_level]: [ALL_ENABLE]
[persist.sys.timezone]: [Asia/Shanghai]
[persist.sys.usb.config]: [adb]
[persist.sys.webview.vmsize]: [151675520]
[pm.dexopt.ab-ota]: [speed-profile]
[pm.dexopt.bg-dexopt]: [speed-profile]
[pm.dexopt.boot]: [verify]
[pm.dexopt.first-boot]: [quicken]
[pm.dexopt.inactive]: [verify]
[pm.dexopt.install]: [quicken]
[pm.dexopt.shared]: [speed]
[ril.ecclist]: [911,112,000,08,110,999,118,119,120,122,999110]
[ril.qcril_pre_init_lock_held]: [0]
[rild.libpath]: [/vendor/lib64/libril-qc-qmi-1.so]
[ro.adb.secure]: [1]
[ro.allow.mock.location]: [0]
[ro.audio.flinger_standbytime_ms]: [300]
[ro.audio.monitorRotation]: [true]
[ro.baseband]: [msm]
[ro.bionic.ld.warning]: [1]
[ro.board.platform]: [msm8994]
[ro.boot.baseband]: [msm]
[ro.boot.bootdevice]: [f9824900.sdhci]
[ro.boot.bootloader]: [angler-03.84]
[ro.boot.bootreason]: [reboot]
[ro.boot.console]: [ttyHSL0]
[ro.boot.flash.locked]: [1]
[ro.boot.hardware]: [angler]
[ro.boot.hardware.ddr]: [3072MB,SAMSUNG,LPDDR4]
[ro.boot.hardware.emmc]: [64GB,Toshiba]
[ro.boot.hardware.revision]: [ANGLER-ROW-VN1]
[ro.boot.hardware.sku]: [H1512]
[ro.boot.mode]: [normal]
[ro.boot.radio]: [angler-03.88]
[ro.boot.secure_hardware]: [1]
[ro.boot.serialno]: [CVH7N16125000171]
[ro.boot.verifiedbootstate]: [green]
[ro.boot.veritymode]: [enforcing]
[ro.boot.wifi_cal]: []
[ro.boot.wifimacaddr]: [DC:EE:06:FC:DE:CB]
[ro.bootimage.build.date]: [Fri Apr 26 14:18:22 UTC 2019]
[ro.bootimage.build.date.utc]: [1556288302]
[ro.bootimage.build.fingerprint]: [google/angler/angler:8.1.0/OPM7.181205.001/5080180:user/release-keys]
[ro.bootloader]: [angler-03.84]
[ro.bootmode]: [normal]
[ro.build.characteristics]: [nosdcard]
[ro.build.date]: [Fri Apr 26 14:18:22 UTC 2019]
[ro.build.date.utc]: [1556288302]
[ro.build.description]: [angler-user 8.1.0 OPM7.181205.001 5080180 release-keys]
[ro.build.display.id]: [lineage_angler-userdebug 8.1.0 OPM7.181205.001 98d5e77ab5]
[ro.build.fingerprint]: [google/angler/angler:8.1.0/OPM7.181205.001/5080180:user/release-keys]
[ro.build.flavor]: [lineage_angler-userdebug]
[ro.build.host]: [lineage-runner]
[ro.build.id]: [OPM7.181205.001]
[ro.build.product]: [angler]
[ro.build.selinux]: [0]
[ro.build.tags]: [release-keys]
[ro.build.type]: [user]
[ro.build.user]: [gitlab-runner]
[ro.build.version.all_codenames]: [REL]
[ro.build.version.base_os]: []
[ro.build.version.codename]: [REL]
[ro.build.version.incremental]: [98d5e77ab5]
[ro.build.version.preview_sdk]: [0]
[ro.build.version.release]: [8.1.0]
[ro.build.version.sdk]: [27]
[ro.build.version.security_patch]: [2019-04-05]
[ro.carrier]: [unknown]
[ro.com.google.clientidbase]: [android-google]
[ro.config.alarm_alert]: [Hassium.ogg]
[ro.config.notification_sound]: [Argon.ogg]
[ro.config.ringtone]: [Orion.ogg]
[ro.crypto.fs_crypto_blkdev]: [/dev/block/dm-0]
[ro.crypto.state]: [encrypted]
[ro.crypto.type]: [block]
[ro.dalvik.vm.native.bridge]: [0]
[ro.debuggable]: [0]
[ro.device.cache_dir]: [/data/cache]
[ro.device_owner]: [false]
[ro.expect.recovery_id]: [0xf9c5340839c618531729d3addeb762f88142be04000000000000000000000000]
[ro.facelock.black_timeout]: [700]
[ro.facelock.det_timeout]: [2500]
[ro.facelock.est_max_time]: [600]
[ro.facelock.rec_timeout]: [3500]
[ro.frp.pst]: [/dev/block/platform/soc.0/f9824900.sdhci/by-name/frp]
[ro.hardware]: [angler]
[ro.hwui.drop_shadow_cache_size]: [6]
[ro.hwui.gradient_cache_size]: [1]
[ro.hwui.layer_cache_size]: [48]
[ro.hwui.path_cache_size]: [32]
[ro.hwui.r_buffer_cache_size]: [8]
[ro.hwui.text_large_cache_height]: [1024]
[ro.hwui.text_large_cache_width]: [2048]
[ro.hwui.text_small_cache_height]: [1024]
[ro.hwui.text_small_cache_width]: [1024]
[ro.hwui.texture_cache_flushrate]: [0.4]
[ro.hwui.texture_cache_size]: [72]
[ro.lineage.build.version]: [15.1]
[ro.lineage.build.version.plat.rev]: [0]
[ro.lineage.build.version.plat.sdk]: [9]
[ro.lineage.device]: [angler]
[ro.lineage.display.version]: [15.1-20190426-NIGHTLY-angler]
[ro.lineage.releasetype]: [NIGHTLY]
[ro.lineage.version]: [15.1-20190426-NIGHTLY-angler]
[ro.lineagelegal.url]: [https://lineageos.org/legal]
[ro.min_freq_0]: [384000]
[ro.min_freq_4]: [384000]
[ro.modversion]: [15.1-20190426-NIGHTLY-angler]
[ro.oem_unlock_supported]: [1]
[ro.opengles.version]: [196610]
[ro.product.board]: [angler]
[ro.product.brand]: [google]
[ro.product.cpu.abi]: [arm64-v8a]
[ro.product.cpu.abilist]: [arm64-v8a,armeabi-v7a,armeabi]
[ro.product.cpu.abilist32]: [armeabi-v7a,armeabi]
[ro.product.cpu.abilist64]: [arm64-v8a]
[ro.product.device]: [angler]
[ro.product.first_api_level]: [23]
[ro.product.locale]: [en-US]
[ro.product.manufacturer]: [Huawei]
[ro.product.model]: [Nexus 6P]
[ro.product.name]: [angler]
[ro.property_service.version]: [2]
[ro.qc.sdk.audio.fluencetype]: [fluence]
[ro.recovery_id]: [0x09e4c08d0df302e302f55d7b801dce1e23339cb4000000000000000000000000]
[ro.revision]: [0]
[ro.ril.force_eri_from_xml]: [true]
[ro.ril.svdo]: [false]
[ro.ril.svlte1x]: [false]
[ro.secure]: [1]
[ro.serialno]: [CVH7N16125000171]
[ro.sf.lcd_density]: [560]
[ro.storage_manager.enabled]: [true]
[ro.telephony.call_ring.multiple]: [0]
[ro.telephony.default_cdma_sub]: [0]
[ro.telephony.default_network]: [10]
[ro.telephony.get_imsi_from_sim]: [true]
[ro.treble.enabled]: [false]
[ro.vendor.build.date]: [Fri Oct 19 16:45:06 UTC 2018]
[ro.vendor.build.date.utc]: [1539967506]
[ro.vendor.build.fingerprint]: [google/angler/angler:8.1.0/OPM7.181205.001/5080180:user/release-keys]
[ro.vendor.extension_library]: [libqti-perfd-client.so]
[ro.vendor.product.brand]: [google]
[ro.vendor.product.device]: [angler]
[ro.vendor.product.manufacturer]: [Huawei]
[ro.vendor.product.model]: [Nexus 6P]
[ro.vendor.product.name]: [lineage_angler]
[ro.wifi.channels]: []
[ro.zygote]: [zygote64_32]
[security.perf_harden]: [1]
[service.bootanim.exit]: [1]
[service.sf.present_timestamp]: [0]
[sys.boot_completed]: [1]
[sys.lineage_settings_secure_version]: [1]
[sys.listeners.registered]: [true]
[sys.logbootcomplete]: [1]
[sys.oem_unlock_allowed]: [1]
[sys.qcom.devup]: [1]
[sys.rescue_boot_count]: [1]
[sys.retaildemo.enabled]: [0]
[sys.sysctl.extra_free_kbytes]: [43200]
[sys.sysctl.tcp_def_init_rwnd]: [60]
[sys.usb.config]: [adb]
[sys.usb.configfs]: [0]
[sys.usb.controller]: [f9200000.dwc3]
[sys.usb.ffs.max_read]: [262144]
[sys.usb.ffs.max_write]: [262144]
[sys.usb.ffs.mtp.ready]: [1]
[sys.usb.ffs.ready]: [1]
[sys.usb.mtp.device_type]: [3]
[sys.usb.state]: [adb]
[sys.user.0.ce_available]: [true]
[telephony.lteOnCdmaDevice]: [1]
[tombstoned.max_tombstone_count]: [50]
[vidc.debug.perf.mode]: [2]
[vidc.enc.dcvs.extra-buff-count]: [2]
[vold.decrypt]: [trigger_restart_framework]
[vold.has_adoptable]: [0]
[vold.has_quota]: [0]
[vold.post_fs_data_done]: [1]
[wifi.interface]: [wlan0]
```

**Comment by tanghengvip** [comment]
我开启这模块啥网页都打不开，但接口都是正常的，不知道咋修

**Comment by lurumdare** [comment]
Install Fiddler certificate.

**Comment by BiteFoo** [comment]
同@lurumdare说的，装个代理的证书即可，我用的是mitmproxy,因此直接安装了mitmproxy的手机代理，即可正常使用。

**Comment by lurumdare** [comment]
@BiteFoo fiddler works good.

**Comment by tanghengvip** [comment]
https://mega.nz/#!uvp1xCJJ!CD_D27Fy9OIW60Bf0GPKN14xf50lKVXG2Tt298RjW8E
Use this one!!! everything will be ok.
